#!/bin/bash


#source /root/.data/source/funcInput
#source /root/.data/source/funcEmuterm
#source /root/.data/source/funcVar
source /root/.data/source/allFunc
scrollLimitDown=5
networkStatusCheck
controller=0
if (( $controller < 1 ))
then
	importController
fi

sleep 2

while true
do
	inputDs3
	inputDs3ToMove
	sleepSmall
	clear
	echo " "
	networkStatus
	echo " "
	echo "             ____________________________________________________________"
	echo "             [====Menu===================  |||===Terminal================]"
	echo "             [---${y1Value[0]}-->${menuMain[${y1Value[0]}]} = ${y1Value[0]} "
	echo "             [=  ${y1Value[1]}   ${menuMain[${y1Value[1]}]}"
	echo "             [=  ${y1Value[2]}   ${menuMain[${y1Value[2]}]}"
	echo "             [=  ${y1Value[3]}   ${menuMain[${y1Value[3]}]}"
	echo "             [=  ${y1Value[4]}   ${menuMain[${y1Value[4]}]}"
	echo "             [=  ${y1Value[5]}   ${menuMain[${y1Value[5]}]}"
	echo "             [=  ${y1Value[6]}   ${menuMain[${y1Value[6]}]}"
	echo "             [=  ${y1Value[7]}   ${menuMain[${y1Value[7]}]}"
	echo "             [=  ${y1Value[8]}   ${menuMain[${y1Value[8]}]}"
	echo "             [=  ${y1Value[9]}   ${menuMain[${y1Value[9]}]}"
	echo "             [=  ${y1Value[10]}   ${menuMain[${y1Value[10]}]}"	
	echo "             [=  ${y1Value[11]}   ${menuMain[${y1Value[11]}]}"
	echo "             [=  ${y1Value[12]}   ${menuMain[${y1Value[12]}]}"
	echo "             [=  ${y1Value[13]}   ${menuMain[${y1Value[13]}]}"
	echo "             [=  ${y1Value[14]}   ${menuMain[${y1Value[14]}]}"
	echo "             [=  ${y1Value[15]}   ${menuMain[${y1Value[15]}]}"
	echo "             [=  ${y1Value[16]}   ${menuMain[${y1Value[16]}]}"
	
	buttonStatus

	menuMainSelect
	menuBack
done
